version: "3.9"
services:
  postgres:
    image: postgres:14.8-alpine3.18
    environment:
      POSTGRES_DB: "higharchdb"
      POSTGRES_USER: "higharchpguser"
      POSTGRES_PASSWORD: "higharchpgpwd"
      PGDATA: "/var/lib/postgresql/data/pgdata"
    volumes:
      - ./init_db:/docker-entrypoint-initdb.d
      - higharchdb-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  cache-redis:
    image: redis:7.2.5-alpine
    restart: always
    ports:
      - '6379:6379'
    command: redis-server --save 20 1 --loglevel warning --requirepass higharchredispwd
    volumes:
      - higharchdb-cache:/data

  rabbitmq:
    image: rabbitmq:3.13.4-management
    hostname: rabbitmq
    restart: always
    environment:
      - RABBITMQ_DEFAULT_USER=higharchrabbituser
      - RABBITMQ_DEFAULT_PASS=higharchrabbitpwd
      - RABBITMQ_SERVER_ADDITIONAL_ERL_ARGS=-rabbit log_levels [{connection,error},{default,error}] disk_free_limit 2147483648
    volumes:
      - higharchdb-rabbit:/var/lib/rabbitmq
    ports:
      - 15672:15672
      - 5672:5672

  app:
    build:
      dockerfile: Dockerfile
      context: .
    environment:
      POSTGRES_DB: "higharchdb"
      POSTGRES_USER: "higharchpguser"
      POSTGRES_PASSWORD: "higharchpgpwd"
      POSTGRES_HOST: "postgres"
      POSTGRES_PORT: "5432"
      REDIS_HOST: "cache-redis"
      REDIS_PORT: "6379"
      REDIS_PASSWORD: "higharchredispwd"
      RABBITMQ_PORT: "5672"
      RABBITMQ_HOST: "rabbitmq"
      RABBITMQ_USER: "higharchrabbituser"
      RABBITMQ_PASS: "higharchrabbitpwd"
      APP_PORT: "8080"
    volumes:
      - .:/app
    ports:
      - "8080:8080"
    depends_on:
      - postgres
      - cache-redis
      - rabbitmq

volumes:
  higharchdb-data:
  higharchdb-cache:
  higharchdb-rabbit:
