version: "3.9"
services:
  postgres:
    image: postgres:14.8-alpine3.18
    environment:
      POSTGRES_DB: "higharchdb"
      POSTGRES_USER: "higharchpguser"
      POSTGRES_PASSWORD: "higharchpgpwd"
      PGDATA: "/var/lib/postgresql/data/pgdata"
    volumes:
      - ./init_db:/docker-entrypoint-initdb.d
      - higharchdb-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  cache-redis:
    image: redis:7.2.5-alpine
    restart: always
    ports:
      - '6379:6379'
    command: redis-server --save 20 1 --loglevel warning --requirepass higharchredispwd
    volumes:
      - higharchdb-cache:/data

  app:
    build:
      dockerfile: Dockerfile
      context: .
    environment:
      POSTGRES_DB: "higharchdb"
      POSTGRES_USER: "higharchpguser"
      POSTGRES_PASSWORD: "higharchpgpwd"
      POSTGRES_HOST: "postgres"
      POSTGRES_PORT: "5432"
      REDIS_HOST: "cache-redis"
      REDIS_PORT: "6379"
      REDIS_PASSWORD: "higharchredispwd"
      APP_PORT: "8080"
    volumes:
      - .:/app
    ports:
      - "8080:8080"
    depends_on:
      - postgres
      - cache-redis

volumes:
  higharchdb-data:
  higharchdb-cache:
